name: GitHub CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_fixture_factories
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.0
          extensions: mbstring, intl, apcu, pdo_sqlite, pdo_mysql, pdo_pgsql
          ini-values: apc.enable_cli = 1

      - name: Create DB
        run: sudo service mysql start && mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE IF NOT EXISTS test_fixture_factories;'

      - name: Validate composer.json
        run: composer validate

      - name: Install lowest dependencies
        run: composer update --prefer-dist --no-progress --no-suggest --prefer-lowest --prefer-stable

      - name: Run tests on sqlite
        run: composer run-tests-sqlite

      - name: Run tests on mysql
        run: composer run-tests-mysql root root

      - name: Run tests on postgres
        run: composer run-tests-postgres root root

      - name: Install highest dependencies
        run: composer update --prefer-dist --no-progress --no-suggest --prefer-stable

      - name: Run tests on sqlite
        run: composer run-tests-sqlite

      - name: Run tests on mysql
        run: composer run-tests-mysql root root

      - name: Run tests on postgres
        run: composer run-tests-postgres root root

      - name: Install dev dependencies
        run: composer update --prefer-dist --no-progress --no-suggest

      - name: Run tests on sqlite
        run: composer run-tests-sqlite
        continue-on-error: true

      - name: Run tests on mysql
        run: composer run-tests-mysql root root
        continue-on-error: true

      - name: Run tests on postgres
        run: composer run-tests-postgres root root
        continue-on-error: true